### ISSUE TITLE
docs: update dependabot workflow to add commit message and proper label

### ISSUE THREAD

**Issue by Anmol-Baranwal** [SrijanShovit/carbonops-v2#232]
### Description

> Current One:

```yml
version: 2
updates:
  # Update GitHub Actions and dependencies
  - package-ecosystem: "github-actions"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
```

Firstly, it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

Like this: (looks clean and according to conventions)
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5f7ae417-b0d8-44bc-89e0-0ba02621979e)

<hr>

I will add the changes with detailed instructions.

> I will do this contribution under GSSoC'23. So, please assign me and I will make a PR.
